apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-gidtxdpy
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-gidtxdpy:d900d065d902b76b4dab6cf561321d96de963976@sha256:972dc438fc0150901ee73383931fa8a4df60af83749e25a6bd6d4494bb5b08a7
        name: container-image  
